services:
  web:
    build: .
    container_name: django_app
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
  celery_beat:
    build: .
    command: bash -c "sleep 15 && celery -A core beat -l info"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  db_data: